# Generated by Django 3.1.5 on 2021-03-22 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('Infomative', 'Informative'), ('Events', 'Events'), ('Urgent', 'Urgent')], max_length=100)),
                ('description', models.TextField(max_length=2500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
